#!/usr/bin/awk -f

BEGIN {
    mph2vtk["3 tet"] = 10
    mph2vtk["5 prism"] = 13
    mph2vtk["3 vtx"] = 1
    getline
    getline
    getline
    getline
    major = $1
    minor = $2
    getline
    sub(/#.*/, "")
    number_of_tags = $1
    getline
    getline # tags
    getline # number_of_types
    getline
    getline # types
    getline
    getline
    getline
    getline # 0 0 1
    getline # class
    getline # version
    getline # sdim
    getline
    sub(/#.*/, "")
    nv = $1
    getline # lowest mesh vertex index
    getline
    getline
    for (i = 0; i < nv; i++) {
	getline
	x[i] = $1
	y[i] = $2
	z[i] = $3
    }
    getline
    getline
    sub(/#.*/, "")
    nt = $1
    for (i = 0; i < nt; i++) {
	getline
	getline # Type # ...
	getline
	getline
	sub(/#.*/, "")
	sub(/[\t ]*$/, "")
	name[i] = $0
	getline
	getline
	getline
	sub(/#.*/, "")
	np[i] = $1
	getline
	sub(/#.*/, "")
	ne[i] = $1
	getline
	for (j = 0; j < ne[i]; j++) {
	    getline
	    for (k = 0; k < np[i]; k++)
		element[i, j, k] = $(k + 1)
	}
	getline
	getline
	sub(/#.*/, "")
	ng[i] = $1
	getline
	for (j = 0; j < ng[i]; j++) {
	    getline
	}
    }
    print "# vtk DataFile Version 2.0"
    print "mph2vtk"
    print "ASCII"
    print "DATASET UNSTRUCTURED_GRID"
    printf "POINTS %d float\n", nv
    for (i = 0; i < nv; i++)
	print x[i], y[i], z[i]
    Ne = 0
    Nd = 0
    for (i = 0; i < nt; i++) {
	Ne += ne[i]
	Nd += ne[i] * (np[i] + 1)
    }
    printf "CELLS %d %d\n", Ne, Nd
    for (i = 0; i < nt; i++)
	for (j = 0; j < ne[i]; j++) {
	    printf "%d", np[i]
	    for (k = 0; k < np[i]; k++)
		printf " %d", element[i, j, k]
	    printf "\n"
	}
    printf "CELL_TYPES %d\n", Ne
    for (i = 0; i < nt; i++) {
	vtk = mph2vtk[name[i]]
	for (j = 0; j < ne[i]; j++)
	    print vtk
    }
}
