FROM docker.io/nvidia/cuda:11.2.0-cudnn8-devel-ubuntu20.04

ARG MPICH_VERSION=3.1.4

RUN env TZ=Europe/Zurich DEBIAN_FRONTEND=noninteractive apt-get update \
    && env TZ=Europe/Zurich DEBIAN_FRONTEND=noninteractive apt-get -y --fix-missing upgrade

RUN apt-get -y install build-essential \
    wget

RUN cd /tmp \
  && wget -q http://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz \
  && tar -xf mpich-${MPICH_VERSION}.tar.gz \
  && cd mpich-${MPICH_VERSION} \
  && ./configure --disable-fortran --enable-fast=all,O3 --prefix=/usr \
  && echo "Using $(cat /proc/cpuinfo | grep 'model name' | wc -l) processes to build" \
  && make -j$(cat /proc/cpuinfo | grep 'model name' | wc -l) \
  && make install \
  && cd .. \
  && rm -Rf mpich-${MPICH_VERSION}{,.tar.gz}

RUN env TZ=Europe/Zurich DEBIAN_FRONTEND=noninteractive \
    apt-get -y install \
    apt-transport-https \
    git \
    libgsl-dev \
    pkg-config \
    python3-dev \
    python3-matplotlib \
    python3-pip \
    python3-numpy \
    python3-pandas \
    python3-pybind11 \
    python3-scipy
RUN python3 -m pip install mpi4py
RUN cd /tmp \
  && wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
  && dpkg -i packages-microsoft-prod.deb \
  && rm packages-microsoft-prod.deb \
  && apt-get update \
  && apt-get install -y dotnet-sdk-6.0
